### ISSUE TITLE
[Milestone 2 Feedback Fix] Verification

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#108]
Professor's Comment: The verification process needs to be taken on: do not wait to start it. Start it right away, you want to be able to rerun it iteratively. Do not wait!

My comment: Verification in this context involves ensuring that project deliverables meet their specified properties and requirements. So, start the process of verification.

Criteria:
  Anything that has to do with stating a property about your
  deliverables that then needs to be checked goes here. Does your
  project employ testing? Yes: describe what kinds of testing will be
  used, how, when, who, why you do this kind of testing. Have you done
  any walkthroughs of your requirements using scenarios? Who did those?
  Did you find any gaps in the requirements? What remedies did you come
  up with?

  • Validation is not for getting the users' approval. It is so you can
    present the users, clients, stakeholders with what you understood in
    a way that they can give you additional information or insights.
  • Say you understand that a scale is an important tool in the kitchen
    and you give recipe instructions in terms of weight. So, you run
    some specific recipes by a given prospective user, say Berta. Now,
    Berta says that her kitchen scale is currently out of battery and
    that the batteries are hard to come by. Together you come up with
    the idea to add amounts measured by volume.
  • Say you understand that a there is a category that an artwork falls
    into (photo, painting, …). So, you create some specific scenarios
    involving these and present them to a given prospective user, say
    Berta. Now, Berta says that she created an artwork that users
    painting on photos. Together you come up with the idea that there is
    not always a single category for the piece of art. So, you were
    validating the concept that there is a single category for the
    method and you found that the stakeholder did not agree.
  • For example, you think you understand how tasks are assigned in a
    project concerned with supporting students in school with their
    assignments, so you generate specific scenarios that you think could
    happen in the domain. Such a scenario could be: "Student Bruno likes
    to work his school homework every day. The times when he feels most
    productive are from 4pm-6pm. He gets an assignment from his Physics
    class and he estimates that assignment will take 4 hours to
    complete. The assignment is due in 4 days. Before starting on the
    Physics assig…" Then such a scenario is used as a starting point to
    talk to stakeholders, prospective users, … They might come up with
    questions such as "What if Bruno does not do homework on Sundays?"
    or "What if Bruno wants to change an estimate?". The dialog with the
    stakeholders can help you see whether you can accommodate all the
    things that they feel are necessary.
  • "A user can post a recipe successfully" is not entirely verifiable
    by unit tests. Unit tests can test only the units, e.g. objects,
    classes. So you could test whether a specific recipe object's
    "publish" method is successful in ensuring that various "user"
    objects (Berta, Claire, David, Hector) can afterwards "view" this
    recipe.
  • You can test e.g. completeness of your terminology by going over the
    domain description, requirements prescription, software
    architecture, … checking whether all terms you use are defined in
    the terminology.
  • You can validate the terminology e.g. by describing scenarios using
    the terms and getting feedback from stakeholders whether they would
    express the scenarios any different.
  • You want to document why you need to validate or verify something
    and how this will actually be done.
  • Don't just list model-checking as a testing method if you have not
    really thought about it and have clear and specific ideas on how you
    will use it.
  • Also, A/B testing is used with different versions in order to see
    which version is better in some respect (to be defined). Often this
    is used in the context of UI/UX. For example, we may have a web page
    to check out from an online shop. We may hypothesize that putting
    the button to check out in the top right would make it easier for
    visitors to our shop to find it and check out. We might think that
    the time from reaching the page after adding the last item until the
    check out button is pressed is an indicator for how easy it is for
    the visitors to use the check out function. So we prepare an A and a
    B version and we measure, say for a month, how long it takes until
    the button is clicked.

Urgency: 4
Difficulty: 4

**Comment by Adhel-Esteban1** [comment]
Updated this:
Professor's Comment: The verification process needs to be taken on: do not wait to start it. Start it right away, you want to be able to rerun it iteratively. Do not wait!

My comment: Verification in this context involves ensuring that project deliverables meet their specified properties and requirements. So, start the process of verification.

Criteria:
Anything that has to do with stating a property about your
deliverables that then needs to be checked goes here. Does your
project employ testing? Yes: describe what kinds of testing will be
used, how, when, who, why you do this kind of testing. Have you done
any walkthroughs of your requirements using scenarios? Who did those?
Did you find any gaps in the requirements? What remedies did you come
up with?

• Validation is not for getting the users' approval. It is so you can
present the users, clients, stakeholders with what you understood in
a way that they can give you additional information or insights.
• Say you understand that a scale is an important tool in the kitchen
and you give recipe instructions in terms of weight. So, you run
some specific recipes by a given prospective user, say Berta. Now,
Berta says that her kitchen scale is currently out of battery and
that the batteries are hard to come by. Together you come up with
the idea to add amounts measured by volume.
• Say you understand that a there is a category that an artwork falls
into (photo, painting, …). So, you create some specific scenarios
involving these and present them to a given prospective user, say
Berta. Now, Berta says that she created an artwork that users
painting on photos. Together you come up with the idea that there is
not always a single category for the piece of art. So, you were
validating the concept that there is a single category for the
method and you found that the stakeholder did not agree.
• For example, you think you understand how tasks are assigned in a
project concerned with supporting students in school with their
assignments, so you generate specific scenarios that you think could
happen in the domain. Such a scenario could be: "Student Bruno likes
to work his school homework every day. The times when he feels most
productive are from 4pm-6pm. He gets an assignment from his Physics
class and he estimates that assignment will take 4 hours to
complete. The assignment is due in 4 days. Before starting on the
Physics assig…" Then such a scenario is used as a starting point to
talk to stakeholders, prospective users, … They might come up with
questions such as "What if Bruno does not do homework on Sundays?"
or "What if Bruno wants to change an estimate?". The dialog with the
stakeholders can help you see whether you can accommodate all the
things that they feel are necessary.
• "A user can post a recipe successfully" is not entirely verifiable
by unit tests. Unit tests can test only the units, e.g. objects,
classes. So you could test whether a specific recipe object's
"publish" method is successful in ensuring that various "user"
objects (Berta, Claire, David, Hector) can afterwards "view" this
recipe.
• You can test e.g. completeness of your terminology by going over the
domain description, requirements prescription, software
architecture, … checking whether all terms you use are defined in
the terminology.
• You can validate the terminology e.g. by describing scenarios using
the terms and getting feedback from stakeholders whether they would
express the scenarios any different.
• You want to document why you need to validate or verify something
and how this will actually be done.
• Don't just list model-checking as a testing method if you have not
really thought about it and have clear and specific ideas on how you
will use it.
• Also, A/B testing is used with different versions in order to see
which version is better in some respect (to be defined). Often this
is used in the context of UI/UX. For example, we may have a web page
to check out from an online shop. We may hypothesize that putting
the button to check out in the top right would make it easier for
visitors to our shop to find it and check out. We might think that
the time from reaching the page after adding the last item until the
check out button is pressed is an indicator for how easy it is for
the visitors to use the check out function. So we prepare an A and a
B version and we measure, say for a month, how long it takes until
the button is clicked.

Urgency: 4
Difficulty: 4

**Comment by Adhel-Esteban1** [comment]
Given that the descriptions given in the criteria are unclear and confusing, here's a simplified way to think about this. 
- Verification checks if we’re meeting the requirements stated earlier. Kinda like ticking checkboxes.  
- ⁠Validation looks at the bigger picture and checks if we’re actually solving the problem, if it delivers on the promise and has value for the stakeholders. 

Now, I tried to simplify the instructions given on the criteria:

- Testing Talk: Testing is the backbone of quality assurance. Who's leading the testing charge? What specific tests are we running? Think unit tests, integration tests, system tests, and acceptance tests. How are we conducting these tests? Are we automating them or doing them manually? When are we running these tests? At each stage of development or at specific milestones? And most importantly, why are we testing? To catch bugs early, ensure functionality, and deliver a polished product.
- Requirements Rundown: Walking through project requirements is like laying the foundation of a building. Who's involved in this process? Are stakeholders, developers, and testers all on board? Did we find any gaps or inconsistencies in the requirements? If so, how did we address them? Did we clarify with stakeholders, revise the requirements document, or adjust our approach?
- Validation Voyage: Validation is about confirming that we're on the right track. Share examples of how you validated your understanding with stakeholders. Did you add volume measurements to recipes based on user feedback? Did you discover that artwork doesn't neatly fit into single categories through user interaction? Detail these experiences and how they shaped your project direction.
- Scenario Scrutiny: Scenarios help us understand real-world usage. Share specific scenarios from your project domain. How did stakeholders react? Did they raise questions or concerns? Use these scenarios as conversation starters to uncover hidden requirements or edge cases.
- Unit Test Uproar: Unit testing is about breaking down your code into manageable chunks. Dive deep into how you tested individual recipe components. Did Berta, Claire, David, and Hector all have access to the published recipe? Explain your testing strategy and any challenges you faced.
- Terminology Tune-up: Clear communication is key. Take a thorough look at your project documentation. Are all terms clearly defined? Did you encounter any ambiguous language? Share how you clarified terminology to ensure everyone is on the same page.
- A/B Analysis: A/B testing is a powerful tool for optimizing user experiences. Detail your A/B testing process. What were the different versions you tested? What metrics did you track? And most importantly, what were the results? Did moving the checkout button improve user engagement? Share your findings and any insights gained from the A/B testing process.

Should any help or questions arise contact me the team leader, the managers, or the professor for clarification.

**Comment by AnthonyMed13** [comment]
Forgot to close this
