### ISSUE TITLE
[Milestone 2 Feedback Fix] Wording

### ISSUE THREAD

**Issue by AnthonyMed13** [uprm-inso4115-2023-2024-s2/semester-project-photofit-a-closet-inventory-app#109]
Comments from Professor: 
- When you describe your project with a "firstly" and a "next" etc. it looks like you are thinking in terms of a sequence of phases instead of of an iterative, looping approach. 
- "As a user" is not a good start for a user story, because everyone will be a user. So, user does not really tell us much.

My comment: The "as a user" remains a bit unclear for the moment as it was not pointed out on milestone 1 feedback, I will get back to this soon. However, in this case, I suggest removing the words that give the impression of the sequential phases. 

Urgency: 1
Difficulty: 1

**Comment by Adhel-Esteban1** [comment]
Added this:
Comments from Professor:

When you describe your project with a "firstly" and a "next" etc. it looks like you are thinking in terms of a sequence of phases instead of of an iterative, looping approach.
"As a user" is not a good start for a user story, because everyone will be a user. So, user does not really tell us much.
My comment: The "as a user" remains a bit unclear for the moment as it was not pointed out on milestone 1 feedback, I will get back to this soon. However, in this case, I suggest removing the words that give the impression of the sequential phases.

Urgency: 1
Difficulty: 1

**Comment by DiegoLIRodriguez** [comment]
I will expand this task in order to edit the entire document to address common literature mistakes and enforce formality/clarity.

**Comment by DiegoLIRodriguez** [comment]
Edited proposed changes and addressed current literary issues. Future additions to documentation will be verified as they are submitted.
